-- Migration 002: Datos iniciales

INSERT INTO units (name) VALUES
  ('g'), ('kg'), ('ml'), ('litro'),
  ('taza'), ('cdta'), ('cda'), ('unidad')
ON CONFLICT (name) DO NOTHING;

INSERT INTO products (name) VALUES
  ('cebolla'),
  ('ajo'),
  ('tomate'),
  ('berenjena'),
  ('pimenton'),
  ('zanahoria'),
  ('repollo'),
  ('albaca'),
  ('perejil'),
  ('cilantro'),
  ('champiñones'),
  ('lechuga'),
  ('choclo'),
  ('zapallo italiano'),
  ('zapallo camote'),
  ('limon'),
  ('palta'),
  ('apio'),
  ('puerro'),
  ('berenjena'),
  ('aceitunas'),
  ('mantequilla'),
  ('mantequilla de mani'),
  ('soja'),
  ('mayonesa'),
  ('mostaza'),
  ('ciboulete'),
  ('huevo'),
  ('carne vacuno'),
  ('pollo'),
  ('chancho'),
  ('porotos'),
  ('lentejas'),
  ('garbanzos'),
  ('arvejas'),
  ('harina'),
  ('leche'),
  ('crema'),
  ('naranja'),
  ('platano'),
  ('pepino fruta'),
  ('mango'),
  ('frutilla'),
  ('uvas'),
  ('manjar'),
  ('aceite de oliva'),
  ('fideos integrales'),
  ('fideos chinos'),
  ('arroz integral'),
  ('quinoa'),
  ('pescado'),
  ('jamon'),
  ('queso')
ON CONFLICT (name) DO NOTHING;
